apiVersion: v1
kind: Service
metadata:
  name: {{ include "spegel.fullname" . }}
  namespace: {{ include "spegel.namespace" . }}
  labels:
    app.kubernetes.io/component: metrics
  {{- with .Values.service.metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: spegel
    {{- include "spegel.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spegel.fullname" . }}-registry
  namespace: {{ include "spegel.namespace" . }}
  labels:
  {{- if or (and (not .Values.service.registry.usePreferSameNodeTrafficDistribution) .Values.service.registry.topologyAwareHintsEnabled) .Values.service.registry.annotations }}
  annotations:
    {{- if and (not .Values.service.registry.usePreferSameNodeTrafficDistribution) .Values.service.registry.topologyAwareHintsEnabled }}
    service.kubernetes.io/topology-mode: "auto"
    {{- end }}
    {{- with .Values.service.registry.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: spegel
    {{- include "spegel.selectorLabels" . | nindent 4 }}
  ports:
    - name: registry
      port: {{ .Values.service.registry.port }}
      targetPort: registry
      nodePort: {{ .Values.service.registry.nodePort }}
      protocol: TCP
  {{- if .Values.service.registry.usePreferSameNodeTrafficDistribution }}
  trafficDistribution: PreferSameNode
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spegel.fullname" . }}-bootstrap
  namespace: {{ include "spegel.namespace" . }}
  labels:
  {{- with .Values.service.bootstrap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: spegel
    {{- include "spegel.selectorLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: router
      port: {{ .Values.service.router.port }}
      protocol: TCP
