---
# Source: spegel/templates/post-delete-hook.yaml
apiVersion: v1
kind: Service
metadata:
  name: spegel-cleanup
  namespace: kube-system
  labels:
    app.kubernetes.io/component: cleanup
spec:
  selector:
    app.kubernetes.io/component: cleanup
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: readiness
      port: 8080
      protocol: TCP
---
# Source: spegel/templates/post-delete-hook.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spegel-cleanup
  namespace: kube-system
  labels:
    app.kubernetes.io/component: cleanup
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: cleanup
      app.kubernetes.io/name: spegel
      app.kubernetes.io/instance: spegel
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cleanup
        app.kubernetes.io/name: spegel
        app.kubernetes.io/instance: spegel
    spec:
      securityContext:
        {}
      priorityClassName: system-node-critical
      containers:
      - name: cleanup
        image: "muicoder/spegel:stable"
        imagePullPolicy: IfNotPresent
        args:
          - cleanup
          - --containerd-registry-config-path=/var/lib/rancher/k3s/agent/etc/containerd/certs.d
          - --addr=:8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: readiness
        ports:
          - name: readiness
            containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: containerd-config
            mountPath: /var/lib/rancher/k3s/agent/etc/containerd/certs.d
      volumes:
        - name: containerd-config
          hostPath:
            path: /var/lib/rancher/k3s/agent/etc/containerd/certs.d
            type: DirectoryOrCreate
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
---
# Source: spegel/templates/post-delete-hook.yaml
apiVersion: v1
kind: Pod
metadata:
  name: spegel-cleanup-wait
  namespace: kube-system
  labels:
    app.kubernetes.io/component: cleanup-wait
spec:
  containers:
    - name: cleanup-wait
      image: "muicoder/spegel:stable"
      imagePullPolicy: IfNotPresent
      args:
        - cleanup-wait
        - --probe-endpoint=spegel-cleanup.kube-system.svc.cluster.local.:8080
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
